deployment in server

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -34,7 +34,7 @@ jobs:
         with:
           context: .
           push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/bookstagram-backend:latest
+          tags: ${{ secrets.DOCKER_USERNAME }}/playapp-backend:latest
 
       # Step 7: Setup SSH for EC2
       - name: Setup SSH for EC2
@@ -61,16 +61,17 @@ jobs:
             fi
             
             echo 'Pulling Docker image...'
-            docker pull ${{ secrets.DOCKER_USERNAME }}/bookstagram-backend:latest || { echo 'Docker pull failed'; exit 1; }
+            docker pull ${{ secrets.DOCKER_USERNAME }}/playapp-backend:latest || { echo 'Docker pull failed'; exit 1; }
     
             echo 'Stopping existing container...'
-            docker stop bookstagram-backend || true 
-            docker rm bookstagram-backend || true
+            docker stop playapp-backend || true 
+            docker rm playapp-backend || true
     
             echo 'Running new container...'
-            docker run -d -p 8000:8000 --name bookstagram-backend \
+            docker run -d -p 8000:8000 --name playapp-backend \
               -e MONGO_URL='${{ secrets.MONGO_URL }}' \
               -e PORT='${{ secrets.PORT }}' \
+              -e WEATHER_API_KEY='${{ secrets.WEATHER_API_KEY }}' \
               -e NEXT_PUBLIC_APP_URL='${{ secrets.NEXT_PUBLIC_APP_URL }}' \
               -e RESEND_API_KEY='${{ secrets.RESEND_API_KEY }}' \
               -e COMPANY_RESEND_GMAIL_ACCOUNT='${{ secrets.COMPANY_RESEND_GMAIL_ACCOUNT }}' \
@@ -79,11 +80,12 @@ jobs:
               -e FROMPHONENUMBER='${{ secrets.FROMPHONENUMBER }}' \
               -e AUTH_SECRET='${{ secrets.AUTH_SECRET }}' \
               -e JWT_SALT='${{ secrets.JWT_SALT }}' \
+              -e JWT_SECRET_PHONE='${{ secrets.JWT_SECRET_PHONE }}' \
               -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
               -e AWS_REGION='${{ secrets.AWS_REGION }}' \
               -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
               -e AWS_BUCKET_NAME='${{ secrets.AWS_BUCKET_NAME }}' \
-              ${{ secrets.DOCKER_USERNAME }}/bookstagram-backend:latest || { echo 'Docker run failed'; exit 1; }
+              ${{ secrets.DOCKER_USERNAME }}/playapp-backend:latest || { echo 'Docker run failed'; exit 1; }
 
             echo 'Container running successfully'
     
